### ISSUE TITLE
Linux status, next steps and design questions. 

### ISSUE THREAD

**Issue by PetrosKataras** [chaoticbob/Cinder#42]
Hey, 
thanks for your work on this. I ve been interested on running cinder on Linux for quite some time and I made an initial port that you can find here as mentioned also on the forum ( also cmake and glfw-based ):  
https://github.com/PetrosKataras/Cinder

I would be interested to help on the Linux side if you are interested. I had a quick look today and I was able to build the library but not able to link the BasicApp. I m testing on 64bit xubuntu 14.04. I think the cmake configuration can be simplified a lot and I could help with this I think. Also it would be interesting to hear about your decision to include the source of third party libs ( glfw, freetype ). I know that the cinder core team prefers to go this way on OS X and Windows but I personally think that this goes against the classic Linux workflow where package managers play an integral part. Also this could potentially help with 32bit vs 64bit link issues.

Also a roadmap of what is there already and what would be your plan for the next steps would be great. Anyways, I am opening this issue just to start a discussion and hear your thoughts regarding future development. It would be great to have a fully-featured Linux port of Cinder in *near* the future :).

Cheers,
Petros

**Comment by chaoticbob** [comment]
Hey Petros,

Thanks for taking a look and putting some work into getting a more consistent usage of CMake into the Linux side of things. You've brought up some really good points and it's some that I've discussed with a few others as I've been tinkering with the Linux port

I am totally aware that Linux users normally like to lean on the installed system libraries as opposed to having various libraries embedded into each other. I've been thinking about this since we've briefly spoke about it. The conclusion that I've reached (for the time being) is that it's going Cinder for Linux will be usable both ways, with Cinder's packaged 3rd party libraries and system owned ones - with some caveats. First caveat: default behavior will be Cinder's packaged 3rd party libraries. The reasoning for this is not anything more complicated than dev priority for various platforms other than x86_64 and the availability of human power. Moving parts have to be minimized. That being said, would like to work with you (if you're willing) to develop a way to make enabling usage of system libs as easy as one flag. I think both behaviors can be safely tucked away in some CMake magic. That brings us to the second caveat: there is no guarantee system libs will work. I'll test what I can - and with your help, we can expand this hypothetical list.

I haven't really ran into a problem with the 32bit vs 64bit issue. Everything that ran for me on Ubuntu 15.04 ran on the TK1 using Ubuntu 14.04. Some internal parts of Cinder had to be tweaked. Those changes haven't been incorporated yet. 

The only certain thing I can say about the road map of Cinder for Linux is that x86_64, arm32, and arm64 all carry the same weight...whenever arm64 becomes avail. This means SBCs will have the same priority as Desktop. 

My goal is to make getting onto Linux as painless as possible - but at the same time leaving the door open for advanced users, such as yourself, being able to work in the ways that you prefer. This will not be perfect the first go around. Any help you can offer would be very much appreciated with the understand that it will benefit both you and Cinder for Linux. :) 

Hai

**Comment by PetrosKataras** [comment]
Sounds reasonable.. The ability to switch between system installed dependencies and packaged sources is an option that I haven't encountered before I think but we could try it out and see how this works :) I could actually try to sketch something, as you said it shouldn't be a big deal I think.. Back home I have an RPi2 and I could also give it a try there to see how the build system works. For the 32bit/64bit thing is that when I first tried to build cinder with the initial CMake configuration I was getting link errors from boost that indicated that the library was built 32bit with me running on a 64bit VM. I didn't investigate more though and just swapped it with the system installed boost.

I m with you on trying to make the experience as smooth as possible while leaving the possibility for advance usage also and I think with its quite achievable with the help of CMake. 

Regarding future development I suppose that video support would be an important one ? The last year I had the 'chance' to work with GStreamer so I think I could probably be of some help on that side.

**Comment by chaoticbob** [comment]
re: 32bit vs 64bit. Ahh I get what you meant now. My apologies! I didn't build the boost libs for 32-bit x86 (or x86_64). I was hoping clang would default to 64bit, but it may not have. I'll check the build flags to make sure that the 'bitness' is derived from uname. You may have also forked it before I started to clean that bit of it up. You should start seeing directories for x86, x86_64, armv7 (hard float), and armv8 (eventually). 

It makes me smile to read that you feel this way about video. :) You are absolutely right. Video is vital and should be a first class citizen for any Cinder port. It would be totally amazing if we could dig into GStreamer, with you taking the lead of course. Andrew and I have discussed GStreamer before, and it feels like the right move for Linux.

**Comment by PetrosKataras** [comment]
Actually I had a look on the issue and it doesn't seem related to a 64/32bit inconsistency. The libraries are 64bit indeed. I think the problem is that the boost libs where built with `libc++` which is an issue if you try to compile cinder with `libstdc++` which is the default for Linux.

**Comment by richardeakin** [comment]
Re: shipping thirdparty dependencies - I think one of the big reasons for this choice is that in a few cases we're using these dependencies on non-linux machines as well, and our lives become much easier if the versions match. It appears that many times even Ubuntu, one of the most progressive linux distros, is a step or two behind the version we'd like to use on Mac or Windows of the same library. That, and just having precise control over the dep version simplifies things. Also we can easily mod it if necessary.

Providing cmake flags that let the user opt out of using the shipped copy, and instead use for example cmake modules to configure that dependency, seems doable. Though I imagine it might require extra code for the differences in dependency versions, if that comes up.  Or, we can restrict the version from cmake?

**Comment by PetrosKataras** [comment]
I understand the reasoning of wanting to be consistent with version numbers across platforms so I am personally fine as long as there is also a mechanism that allows you to switch to system installed libs. I made an initial attempt [here] (https://github.com/PetrosKataras/Cinder/commit/698fe10e7f421279ddfc669904302ea6c9789890) which works in principle but I ran into this linking issue above. In this commit you can also see that for boost for example you can specify minimum version number ( you can also specify exact ) and individual components so restricting should not be an issue.

**Comment by chaoticbob** [comment]
re: libc++ (and libc++abi) vs libstdc++

For a while I wasn't able to track down conclusive information regarding the sate of libc++ on Linux...so I just wrote a bunch of code one day to test the limits. It's looking that libc++ and libc++abi are not 100% on Linux as a whole yet. But we can still use clang and have ti just use libstdc++. This means GNUSTL...so some care has to be taken. This also means that we'll be reliant on certain GCC versions and their corresponding libstdc++ friends. From what I've discovered so far, it's looking like the minimum version of the GCC that's required is 4.8.4 (although to be perfectly safe, 4.9 should be used).  

I'll collect the thoughts here and put them into a Wiki soon.

**Comment by PetrosKataras** [comment]
AFAIK if we are consistent and go with libstdc++ for cinder and its dependencies on Linux we should be fine since this is the default and more matured on the Linuxland. What we have to keep in mind is ABI incompatibilities between different libstdc++ versions. The versions that ship with gcc4.8 ( * untu 14.04 ), gcc4.9( 14.10 ) and gcc5.1( 15.10 ) have some implementations different and in general it is not advised to try to mix code that was built from different major compiler versions. See more info [here](https://bugs.launchpad.net/ubuntu/+source/gcc-4.9/+bug/1329089). At least from gcc5.0 on, you can still force the old ABI in newer libstdc++ versions through the `_GLIBCXX_USE_CXX11_ABI` macro though. Some info [here](https://gcc.gnu.org/gcc-5/changes.html#libstdcxx).

**Comment by chaoticbob** [comment]
You're right. I think for the time being, we're going to pick the version of libstdc++ that has the path of least resistance for each platform. Once we're pass the hurdle of "is it working" we can explore other options as time allows. The way I'm currently approaching this is that unless there is an absolute platform restriction,  libstdc++ from gcc4.9 is the minimum version. The only exception I've made to this is the TK1, which isn't away to use gcc4.9 with reasonable ease. On the RPI2, one can replace the wheezy repos with jessie and pull in gcc4.9.3. 

libstdc++ from gcc4.8 presents a problem due toe the regex that is used in the ShaderPreprocessor. 

Also, as much as we're able to, the Cinder source should not be peppered with different #ifdefs of various libstdc++ macros. Cinder on the other platforms have functioned on a deprecation model as far as compilers and the passing of time, the Linux port should not deviate from this.
